public states_dict

"""
A Dictionary of States/UTs that can appear in the data set. The keys will be returned in the cleaning steps, and the values can be matched in the underlying datasets.
"""
states_dict = Dict(
    "A&N Island" => ["A&N Island", "Andaman and Nicobar Islands"],
    "Andaman" => ["Andaman"],
    "Andhra Pradesh" => ["Andhra Pradesh"],
    "Arunachal Pradesh" => ["Arunachal Pradesh"],
    "Assam" => ["Assam"],
    "Bihar" => ["Bihar"],
    "Chandigarh" => ["Chandigarh"],
    "Chhattisgarh" => ["Chhattisgarh"],
    "Dadra and Nagar Haveli and Daman and Diu" => ["Dadra and Nagar Haveli and Daman and Diu"],
    "Delhi" => ["Delhi"],
    "Goa" => ["Goa"],
    "Gujarat" => ["Gujarat"],
    "Haryana" => ["Haryana"],
    "Himachal Pradesh" => ["Himachal Pradesh", "HP"],
    "Jammu & Kashmir" => ["Jammu & Kashmir", "Jammu Kashmir"],
    "Jharkhand" => ["Jharkhand"],
    "Kamataka" => ["Kamataka"],
    "Karnataka" => ["Karnataka"],
    "Kerala" => ["Kerala"],
    "Madhya Pradesh" => ["Madhya Pradesh", "MP"],
    "Maharashtra" => ["Maharashtra"],
    "Manipur" => ["Manipur"],
    "Meghalaya" => ["Meghalaya"],
    "Mizoram" => ["Mizoram"],
    "Nagaland" => ["Nagaland"],
    "Odisha" => ["Odisha"],
    "Pondichery" => ["Pondichery", "Pudhucherry"],
    "Punjab" => ["Punjab"],
    "Rajasthan" => ["Rajasthan"],
    "Sikkim" => ["Sikkim"],
    "Tamil Nadu" => ["Tamil Nadu", "Tamilnadu"],
    "Telangana" => ["Telangana", "Telanagana"],
    "Uttar Pradesh" => ["Uttar Pradesh", "UP"],
    "Uttarakhand" => ["Uttarakhand"],
    "West Bengal" => ["West Bengal"],
)
